# Generated by Django 5.0.6 on 2024-05-30 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplines', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalBests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_weight', models.IntegerField(default=0)),
                ('constant_weight_bifins', models.IntegerField(default=0)),
                ('constant_weight_nofins', models.IntegerField(default=0)),
                ('free_immersion', models.IntegerField(default=0)),
                ('static_apnea', models.IntegerField(default=0)),
                ('dynamic', models.IntegerField(default=0)),
                ('dynamics_bifins', models.IntegerField(default=0)),
                ('dynamic_nofins', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_bests', to='data.user')),
            ],
        ),
    ]
